### PR TITLE
Update OWNERS

### PR DESCRIPTION
**Pull request by RadekManak**
This PR updates the OWNERS file to the latest version.

### CODE REVIEW

**Comment by RadekManak** [comment]
@racheljpg @vincepri

You need to request openshift-eng org membership.
https://source.redhat.com/groups/public/openshift/openshift_wiki/openshift_onboarding_checklist_for_github

**Comment by racheljpg** [comment]
Thanks @RadekManak, I've made a request

**Comment by damdo** [comment]
Any updates from your request @racheljpg ? How about yours @vincepri ?

**Comment by vincepri** [comment]
Still in the process, should be soon!

**Comment by racheljpg** [comment]
@damdo My request was completed, so I should be a member now.

**Comment by RadekManak** [comment]
@racheljpg Looks like you are still not in the org. Did you accept the invite?

**Comment by racheljpg** [comment]
Hello @RadekManak, sorry for the delay, I was on PTO. I've accepted the invite now - it only came a few days after this. Thanks!

**Review by damdo — COMMENTED** [review]
/lgtm

**Pull request merged**
